### ISSUE TITLE
多GPU并行计算时，st_gcn_networks输出通道数错误

### ISSUE THREAD

**Issue by chaosles** [xincoder/GRIP#10]
Hi~Xin
当我使用多GPU（8个）训练时，st_gcn_networks输出channel错误，设定为64，输出为6(=in_channel)。总是在报错：

```
/home/traffic/anaconda3/envs/GRIP/lib/python3.8/site-packages/torch/nn/modules/container.py:434: UserWarning: Setting attributes on ParameterList is not supported.
  warnings.warn("Setting attributes on ParameterList is not supported.")
#######################################Train
/home/traffic/anaconda3/envs/GRIP/lib/python3.8/site-packages/torch/nn/modules/container.py:489: UserWarning: nn.ParameterList is being used with DataParallel but this is not supported. This list will appear empty for the models replicated on each GPU except the original one.
  warnings.warn("nn.ParameterList is being used with DataParallel but this is not "
Traceback (most recent call last):
  File "/opt/pycharm/pycharm-2020.1.5/plugins/python/helpers/pydev/pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm/pycharm-2020.1.5/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/traffic/GRIP-master/main.py", line 394, in <module>
    run_trainval(model, pra_traindata_path='./train_data.pkl', pra_testdata_path='./test_data.pkl')
  File "/home/traffic/GRIP-master/main.py", line 365, in run_trainval
    train_model(pra_model, all_loader_train,
  File "/home/traffic/GRIP-master/main.py", line 160, in train_model
    predicted = pra_model(pra_x=input_data,
  File "/home/traffic/anaconda3/envs/GRIP/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/traffic/anaconda3/envs/GRIP/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/traffic/anaconda3/envs/GRIP/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/traffic/anaconda3/envs/GRIP/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/traffic/anaconda3/envs/GRIP/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/traffic/anaconda3/envs/GRIP/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/traffic/anaconda3/envs/GRIP/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/traffic/GRIP-master/model.py", line 86, in forward
    now_predict_car = self.seq2seq_car(in_data=graph_conv_feature, last_location=last_position[:,-1:,:], pred_length=pra_pred_length, teacher_forcing_ratio=pra_teacher_forcing_ratio, teacher_location=pra_teacher_location)
  File "/home/traffic/anaconda3/envs/GRIP/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/traffic/GRIP-master/layers/seq2seq.py", line 68, in forward
    encoded_output, hidden = self.encoder(in_data)
  File "/home/traffic/anaconda3/envs/GRIP/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/traffic/GRIP-master/layers/seq2seq.py", line 22, in forward
    output, hidden = self.lstm(input)
  File "/home/traffic/anaconda3/envs/GRIP/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/traffic/anaconda3/envs/GRIP/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 737, in forward
    self.check_forward_args(input, hx, batch_sizes)
  File "/home/traffic/anaconda3/envs/GRIP/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 199, in check_forward_args
    self.check_input(input, batch_sizes)
  File "/home/traffic/anaconda3/envs/GRIP/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 178, in check_input
    raise RuntimeError(
RuntimeError: input.size(-1) must be equal to input_size. Expected 64, got 6

```

**Comment by chaosles** [comment]
我检查了一下原因，看到输入reshape_for_lstm的feature的C正是6，等于我创建model时的in_channel。似乎st_gcn_networks增加的channel无效，这是为什么呢？我对st_gcn_networks设置的out_channel同样是64。我没有检查到哪里出错了。
但使用多个GPU不是必须的。如果您对此有了解的话，可以帮帮我吗？
