### ISSUE TITLE
Error when running main.py

### ISSUE THREAD

**Issue by lylyjy** [xincoder/GRIP#20]
Hi,
When I run main.py, it occurs that:

C:\Users\lenovo\Anaconda3\lib\site-packages\torch\nn\modules\container.py:435: UserWarning: Setting attributes on ParameterList is not supported.
  warnings.warn("Setting attributes on ParameterList is not supported.")
Traceback (most recent call last):
  File "F:/LYL/GRIP-master/main.py", line 357, in <module>
    run_trainval(model, pra_traindata_path='./train_data.pkl', pra_testdata_path='./test_data.pkl')
  File "F:/LYL/GRIP-master/main.py", line 334, in run_trainval
    train_model(pra_model, all_loader_train, pra_optimizer=optimizer, pra_epoch_log='Epoch:{:>4}/{:>4}'.format(now_epoch, total_epoch))
  File "F:/LYL/GRIP-master/main.py", line 134, in train_model
    for iteration, (ori_data, A, _) in enumerate(pra_data_loader):
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "C:\Users\lenovo\Anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\lenovo\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\lenovo\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\lenovo\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\lenovo\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

Do you know the reason?Thanks.

**Comment by lylyjy** [comment]
I have solved it.Thanks.

**Comment by xincoder** [comment]
@lylyjy Glad to hear that you have already solved the problem. Thanks.
